import React from "react"
import { Sarabun } from "next/font/google"
import StyledComponentsRegistry from "../lib/AntdRegistry"

const sarabun = Sarabun({
  subsets: ["thai"],
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={sarabun.className}>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
